import { band, bandColor } from '../format'
import type { FitReport, SkillEvidence, SkillGap } from '../types'

function ScoreRing({ score }: { score: number }) {
  const radius = 42
  const circumference = 2 * Math.PI * radius
  const offset = circumference * (1 - Math.max(0, Math.min(100, score)) / 100)

  return (
    <svg className="ring" width="104" height="104" viewBox="0 0 104 104" role="img"
         aria-label={`Overall fit score ${Math.round(score)} out of 100`}>
      <circle className="ring-track" cx="52" cy="52" r={radius} fill="none" strokeWidth="8" />
      <circle
        className="ring-value"
        cx="52"
        cy="52"
        r={radius}
        fill="none"
        strokeWidth="8"
        strokeLinecap="round"
        stroke={bandColor(band(score))}
        strokeDasharray={circumference}
        strokeDashoffset={offset}
        transform="rotate(-90 52 52)"
      />
      <text className="ring-label" x="52" y="58" textAnchor="middle">
        {Math.round(score)}
      </text>
    </svg>
  )
}

function SkillGroup({
  title,
  description,
  tone,
  items,
}: {
  title: string
  description: string
  tone: 'matched' | 'partial' | 'missing'
  items: { key: string; label: string; hint?: string; required?: boolean }[]
}) {
  return (
    <div className="card skill-group">
      <h4>
        {title}
        <span className="count">{items.length}</span>
      </h4>
      <p>{description}</p>
      {items.length ? (
        <div className="chips">
          {items.map((item) => (
            // `title` alone becomes the accessible name and hides the skill
            // from screen readers behind the tooltip prose, so the label is
            // restated explicitly in aria-label.
            <span
              key={item.key}
              className={`chip ${tone}${item.required ? ' required' : ''}`}
              title={item.hint}
              aria-label={item.hint ? `${item.label}. ${item.hint}` : item.label}
            >
              {item.label}
            </span>
          ))}
        </div>
      ) : (
        <p className="faint" style={{ margin: 0 }}>
          Nothing here.
        </p>
      )}
    </div>
  )
}

interface Props {
  report: FitReport
  onAskAbout: (question: string) => void
}

export default function FitPanel({ report, onAskAbout }: Props) {
  const evidenceChips = (items: SkillEvidence[], required = false) =>
    items.map((item) => ({
      key: item.skill,
      label: item.skill,
      hint: item.resume_snippet ?? undefined,
      required,
    }))

  const gapChips = (items: SkillGap[]) =>
    items.map((item) => ({
      key: item.skill,
      label: item.skill,
      hint: item.reason,
      required: item.importance === 'required',
    }))

  return (
    <div className="fit">
      <div className="card fit-header">
        <ScoreRing score={report.overall_score} />
        <div className="fit-header-body">
          <span className={`verdict ${band(report.overall_score)}`}>{report.verdict}</span>
          <h2>{report.job_title}</h2>
          <p className="fit-caveat">
            Computed from your documents, not generated by the model — the same files always
            give the same score. Weights are a stated judgement call, not a fitted model.
          </p>
        </div>
      </div>

      <div className="card components">
        {report.components.map((component) => (
          <div className="component-row" key={component.name}>
            <div className="component-head">
              <strong>{component.name}</strong>
              <span className="component-score">{component.score.toFixed(0)}</span>
              <span className="component-weight">
                {component.weight > 0 ? `${Math.round(component.weight * 100)}% of score` : 'not scored'}
              </span>
            </div>
            <div className="bar">
              <div
                className={`bar-fill ${band(component.score)}`}
                style={{ width: `${component.weight > 0 ? component.score : 0}%` }}
              />
            </div>
            <p className="component-note">{component.explanation}</p>
          </div>
        ))}
      </div>

      <div className="skill-groups">
        <SkillGroup
          title="Missing"
          description="In the posting, with no matching evidence in your resume. * marks a stated requirement."
          tone="missing"
          items={gapChips(report.missing_skills)}
        />
        <SkillGroup
          title="Partial"
          description="Inferred from related wording rather than stated outright. Check before you claim it."
          tone="partial"
          items={evidenceChips(report.partial_skills)}
        />
        <SkillGroup
          title="Matched"
          description="Named in the posting and evidenced in your resume. Hover to see the line."
          tone="matched"
          items={evidenceChips(report.matched_skills)}
        />
      </div>

      <div className="suggestions">
        <button className="suggestion" onClick={() => onAskAbout('What skills am I missing for this role?')}>
          Explain these gaps
        </button>
        <button className="suggestion" onClick={() => onAskAbout('How does my experience align with this job?')}>
          How do I align?
        </button>
        <button className="suggestion" onClick={() => onAskAbout('What should I prepare for an interview here?')}>
          Prepare me for the interview
        </button>
      </div>
    </div>
  )
}
